# Namespace pÃ«r TechStore me Istio sidecar injection
apiVersion: v1
kind: Namespace
metadata:
  name: techstore
  labels:
    name: techstore
    istio-injection: enabled  # Aktivizo automatic sidecar injection
